language: python
sudo: required

branches:
  only:
  - master
  - dev

matrix:
  include:
    - os: osx
      language: generic
      env: 
        - TOXENV=py37
    - os: osx
      language: generic
      env: 
        - TOXENV=py38
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
      env: 
        - CONDA_UPLOAD=1
        - BUILD_DOCS=1

install:
  # Install the appropriate miniconda depending on the os and miniconda version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source "$HOME"/miniconda/etc/profile.d/conda.sh

  # set configs
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda config --append channels jrgarrahan # temporary lume-model fix
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build

  # log info for debugging
  - conda info -a

  # create build & add to channel
  - conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

  # create env
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file dev-requirements.txt
  - conda activate test-environment

script:
  - pytest
  # Build docs.
  - set -e
  - |
    if [[ "${BUILD_DOCS:=0}" == '1' && "{$LUME_EPICS_REPO:=dev}" == 'slaclab' ]]; then
        mkdocs build -c -d site
        # Publish docs.
        doctr deploy . --deploy-branch-name gh-pages
    fi

after_success:
  - |
    if [[ $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $LUME_EPICS_REPO == 'slaclab' && "{$CONDA_UPLOAD:=0}" == '1' ]]; then
        echo "Uploading to jrgarrahan channel"
        export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN
        anaconda upload bld-dir/noarch/*.tar.bz2
    fi
  - |
    if [[ $LUME_EPICS_REPO == 'dev' && "{$CONDA_UPLOAD:=0}" == '1' ]]; then
        echo "Uploading to jrgarrahan channel"
        export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN
        anaconda upload bld-dir/noarch/*.tar.bz2 --label dev
    fi